### ISSUE TITLE
A high-quality, feature-rich GUI

### ISSUE THREAD

**Issue by meltyness** [meltyness/ratchet-pawl#18]
# Basic requirements
- [x] Add and remove users
    - [ ] Server hotlink to permit secure account creation
- [x] Add and remove servers
- [ ] Monitoring, Troubleshooting, and Alerting
- [x] Command pattern Authorization
- [ ] IP Address access-protection
- [ ] TUI initialization
